---
- hosts: web
  remote_user: ubuntu
  tasks:
    - synchronize: src=../../target/universal/stage/ dest=~/library-management-system delete=yes rsync_opts="--exclude=logs"

- hosts: web
  remote_user: ubuntu
  become: yes
  tasks:
    - template: src=templates/server.service dest=/etc/systemd/system/server.service
      notify:
        - update service list
    - meta: flush_handlers

    - service: name=server state=restarted
    - service: name=server state=started enabled=yes
  handlers:
    - name: update service list
      command: systemctl daemon-reload
