---
# file: web-deploy.yml
- hosts: web
  user: ubuntu

  tasks:
    - template: src=templates/server.service dest=/etc/systemd/system/server.service
      sudo: yes
    - command: systemctl daemon-reload
      sudo: yes
    - service: name=server state=stopped
      sudo: yes
    - command: rm -rf /home/ubuntu/server-0.1-SNAPSHOT
      sudo: yes
    - unarchive: src=../../server/target/universal/server-0.1-SNAPSHOT.tgz dest=~/
    - service: name=server state=started
      sudo: yes
    - command: systemctl enable server
      sudo: yes
