---
- hosts: web
  remote_user: ubuntu
  become: True
  tasks:
    - apt_repository: repo='ppa:webupd8team/java'
    - shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    - apt: pkg=oracle-java8-installer state=latest update_cache=yes
      notify:
        - clean oracle-jdk8-installer
  handlers:
    - name: clean oracle-jdk8-installer
      file: path='/var/lib/apt/lists/*' state=absent
      file: path='/var/cache/oracle-jdk8-installer' state=absent
