---
- hosts: web
  remote_user: ubuntu
  vars:
    service_name: "cjdns"

  tasks:
    - template: src=templates/{{ service_name }}.service dest=/etc/systemd/system/{{ service_name }}.service
      become: yes
    - service: name={{ service_name }} state=stopped
      become: yes
    - file: path=~/{{ service_name }} state=absent
      become: yes
    - synchronize: src=../../../cjdns-ubuntu/ dest=~/{{ service_name }} delete=yes
    - apt: pkg=nodejs state=latest update_cache=yes
      become: yes
    - file: path="/var/lib/apt/lists/*" state=absent
      become: yes
    - service: name={{ service_name }} state=started
      become: yes
    - command: systemctl enable {{ service_name }}
      become: yes
